// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvy0Nlormryg48Ags-aHq-FZholbQahwg',
    appId: '1:878356637984:web:00897e9b64392bfb1f0f45',
    messagingSenderId: '878356637984',
    projectId: 'forgroundservicepoc',
    authDomain: 'forgroundservicepoc.firebaseapp.com',
    databaseURL: 'https://forgroundservicepoc-default-rtdb.firebaseio.com',
    storageBucket: 'forgroundservicepoc.appspot.com',
    measurementId: 'G-R6PM9ZKEKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWM1dV1we1WoejYb1IgFp5-piHlX4WNsk',
    appId: '1:878356637984:android:27a7375f073f6dc71f0f45',
    messagingSenderId: '878356637984',
    projectId: 'forgroundservicepoc',
    databaseURL: 'https://forgroundservicepoc-default-rtdb.firebaseio.com',
    storageBucket: 'forgroundservicepoc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyF67hCuIIcny20hH82kN4B-ml931tP2c',
    appId: '1:878356637984:ios:7cb97f6c8e182b521f0f45',
    messagingSenderId: '878356637984',
    projectId: 'forgroundservicepoc',
    databaseURL: 'https://forgroundservicepoc-default-rtdb.firebaseio.com',
    storageBucket: 'forgroundservicepoc.appspot.com',
    iosClientId: '878356637984-rgms0kbi89n5sci25bfokfa264d4g91s.apps.googleusercontent.com',
    iosBundleId: 'com.example.forgroundServicePoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyF67hCuIIcny20hH82kN4B-ml931tP2c',
    appId: '1:878356637984:ios:7cb97f6c8e182b521f0f45',
    messagingSenderId: '878356637984',
    projectId: 'forgroundservicepoc',
    databaseURL: 'https://forgroundservicepoc-default-rtdb.firebaseio.com',
    storageBucket: 'forgroundservicepoc.appspot.com',
    iosClientId: '878356637984-rgms0kbi89n5sci25bfokfa264d4g91s.apps.googleusercontent.com',
    iosBundleId: 'com.example.forgroundServicePoc',
  );
}
